import { CommerceEntity } from './entities';

type StorMap = {
  [key in CommerceEntity]: string[];
};

const SORT_MAP: StorMap = {
  AdminAddresses_List: [
    'AddressName',
    'ID',
    'DateCreated',
    'CompanyName',
    'FirstName',
    'LastName',
    'Street1',
    'Street2',
    'City',
    'State',
    'Zip',
    'Country',
    'Phone',
  ],
  AdminUsers_List: [
    'LastName',
    'FirstName',
    'Username',
    'ID',
    'Email',
    'DateCreated',
    'PasswordLastSetDate',
  ],
  ApiClients_List: ['ID', 'AppName', 'DefaultContextUserName'],
  SellerApprovalRules_List: [
    'Name',
    'ID',
    'ApprovingGroupID',
    'RuleExpression',
  ],
  Buyers_List: ['ID', 'Name', 'DateCreated'],
  Addresses_List: [
    'AddressName',
    'ID',
    'DateCreated',
    'CompanyName',
    'FirstName',
    'LastName',
    'Street1',
    'Street2',
    'City',
    'State',
    'Zip',
    'Country',
    'Phone',
  ],
  ApprovalRules_List: ['Name', 'ID', 'ApprovingGroupID', 'RuleExpression'],
  CostCenters_List: ['Name', 'ID'],
  CreditCards_List: [
    'ID',
    'CardholderName',
    'CardType',
    'ExpirationDate',
    'DateCreated',
  ],
  Buyers_ListBuyerSellers: ['Name', 'ID'],
  SpendingAccounts_List: ['Name', 'ID'],
  UserGroups_List: ['Name', 'ID'],
  Users_List: [
    'LastName',
    'FirstName',
    'Username',
    'ID',
    'Email',
    'DateCreated',
    'PasswordLastSetDate',
  ],
  Users_ListAcrossBuyers: [
    'LastName',
    'FirstName',
    'Username',
    'ID',
    'Email',
    'DateCreated',
    'PasswordLastSetDate',
  ],
  Cart_ListLineItems: ['DateAdded', 'ID', 'ProductID'],
  Cart_ListPayments: [
    'DateCreated',
    'ID',
    'Type',
    'CreditCardID',
    'SpendingAccountID',
  ],
  Cart_ListPromotions: [
    'Name',
    'ID',
    'Code',
    'StartDate',
    'ExpirationDate',
    'EligibleExpression',
    'ValueExpression',
    'CanCombine',
  ],
  Catalogs_List: ['OwnerID', 'Name', 'ID'],
  Categories_List: ['ID', 'Name'],
  ImpersonationConfigs_List: [
    'ImpersonationBuyerID',
    'ImpersonationGroupID',
    'ImpersonationUserID',
    'BuyerID',
    'GroupID',
    'UserID',
    'SecurityProfileID',
    'ClientID',
    'ID',
  ],
  Incrementors_List: ['ID', 'Name'],
  IntegrationEvents_List: ['ID', 'EventType', 'Name'],
  LineItems_ListAcrossOrders: ['DateAdded', 'ID', 'ProductID'],
  Locales_List: ['ID'],
  Me_ListAddresses: [
    'AddressName',
    'ID',
    'DateCreated',
    'CompanyName',
    'FirstName',
    'LastName',
    'Street1',
    'Street2',
    'City',
    'State',
    'Zip',
    'Country',
    'Phone',
  ],
  Me_ListCatalogs: ['OwnerID', 'Name', 'ID'],
  Me_ListCategories: ['ID', 'Name'],
  Me_ListCostCenters: ['Name', 'ID'],
  Me_ListCreditCards: [
    'ID',
    'CardholderName',
    'CardType',
    'ExpirationDate',
    'DateCreated',
  ],
  Me_ListOrders: [
    'DateSubmitted',
    'DateCreated',
    'ID',
    'FromCompanyID',
    'ToCompanyID',
    'FromUserID',
    'Status',
    'DateApproved',
    'DateDeclined',
    'DateCanceled',
    'DateCompleted',
    'LastUpdated',
    'Subtotal',
    'ShippingCost',
    'TaxCost',
    'PromotionDiscount',
    'Total',
    'IsSubmitted',
  ],
  Me_ListApprovableOrders: [
    'DateSubmitted',
    'DateCreated',
    'ID',
    'FromCompanyID',
    'ToCompanyID',
    'FromUserID',
    'Status',
    'DateApproved',
    'DateDeclined',
    'DateCanceled',
    'DateCompleted',
    'LastUpdated',
    'Subtotal',
    'ShippingCost',
    'TaxCost',
    'PromotionDiscount',
    'Total',
    'IsSubmitted',
  ],
  Me_ListProductCollections: ['Name', 'ID'],
  Me_ListProductCollectionEntries: ['*'],
  Me_ListProducts: ['*'],
  Me_ListSpecs: ['OwnerID', 'Name', 'ID'],
  Me_ListVariants: ['OwnerID', 'Name', 'ID'],
  Me_ListPromotions: [
    'Name',
    'ID',
    'Code',
    'StartDate',
    'ExpirationDate',
    'EligibleExpression',
    'ValueExpression',
    'CanCombine',
  ],
  Me_ListBuyerSellers: ['Name', 'ID'],
  Me_ListShipments: [
    'DateShipped',
    'OwnerID',
    'ID',
    'BuyerID',
    'Shipper',
    'DateDelivered',
    'Cost',
  ],
  Me_ListShipmentItems: [
    'DateShipped',
    'OwnerID',
    'ID',
    'BuyerID',
    'Shipper',
    'DateDelivered',
    'Cost',
  ],
  Me_ListSpendingAccounts: ['Name', 'ID'],
  Me_ListUserGroups: ['Name', 'ID'],
  MessageSenders_List: ['ID', 'Name', 'URL'],
  MessageSenders_ListCCListenerAssignments: [
    'BuyerID',
    'UserGroupID',
    'UserID',
    'MessageConfigName',
    'SupplierID',
  ],
  OpenIdConnects_List: ['ID'],
  OrderReturns_List: [
    'DateSubmitted',
    'DateCreated',
    'DateApproved',
    'DateDeclined',
    'DateCanceled',
    'DateCompleted',
    'LastUpdated',
  ],
  OrderReturns_ListApprovals: [
    'DateCreated',
    'ApprovalRuleID',
    'ApprovingGroupID',
    'Status',
    'DateCompleted',
    'Approver',
  ],
  OrderReturns_ListEligibleApprovers: [
    'LastName',
    'FirstName',
    'Username',
    'ID',
    'Email',
    'DateCreated',
    'PasswordLastSetDate',
  ],
  Orders_List: [
    'DateSubmitted',
    'DateCreated',
    'ID',
    'FromCompanyID',
    'ToCompanyID',
    'FromUserID',
    'Status',
    'DateApproved',
    'DateDeclined',
    'DateCanceled',
    'DateCompleted',
    'LastUpdated',
    'Subtotal',
    'ShippingCost',
    'TaxCost',
    'PromotionDiscount',
    'Total',
    'IsSubmitted',
  ],
  Orders_ListApprovals: [
    'DateCreated',
    'AllowResubmit',
    'ApprovalRuleID',
    'ApprovingGroupID',
    'Status',
    'DateCompleted',
    'Approver',
  ],
  Orders_ListEligibleApprovers: [
    'LastName',
    'FirstName',
    'Username',
    'ID',
    'Email',
    'DateCreated',
    'PasswordLastSetDate',
  ],
  LineItems_List: ['DateAdded', 'ID', 'ProductID'],
  Payments_List: [
    'DateCreated',
    'ID',
    'Type',
    'CreditCardID',
    'SpendingAccountID',
  ],
  Orders_ListPromotions: [
    'Name',
    'ID',
    'Code',
    'StartDate',
    'ExpirationDate',
    'EligibleExpression',
    'ValueExpression',
    'CanCombine',
  ],
  Orders_ListShipments: [
    'DateShipped',
    'OwnerID',
    'ID',
    'BuyerID',
    'Shipper',
    'DateDelivered',
    'Cost',
  ],
  PriceSchedules_List: ['Name', 'ID', 'OwnerID'],
  ProductFacets_List: ['ListOrder', 'ID', 'Name', 'XpPath'],
  Products_List: ['*'],
  InventoryRecords_List: ['ID', 'AddressID'],
  Products_ListSpecs: ['ListOrder', 'Name', 'ID'],
  Products_ListSuppliers: ['ID', 'Name', 'DateCreated'],
  Products_ListVariants: ['ID', 'Name'],
  InventoryRecords_ListVariant: ['ID', 'AddressID'],
  Promotions_List: [
    'Name',
    'ID',
    'Code',
    'StartDate',
    'ExpirationDate',
    'EligibleExpression',
    'ValueExpression',
    'CanCombine',
  ],
  SecurityProfiles_List: ['ID', 'Name'],
  Shipments_List: [
    'DateShipped',
    'OwnerID',
    'ID',
    'BuyerID',
    'Shipper',
    'DateDelivered',
    'Cost',
  ],
  Shipments_ListItems: ['*'],
  Specs_List: ['ListOrder', 'Name', 'ID'],
  Specs_ListOptions: ['ListOrder', 'ID'],
  Specs_ListProductAssignments: [
    'SpecID',
    'ProductID',
    'DefaultOptionID',
    'DefaultValue',
  ],
  Suppliers_List: ['ID', 'Name', 'DateCreated'],
  SupplierAddresses_List: [
    'AddressName',
    'ID',
    'DateCreated',
    'CompanyName',
    'FirstName',
    'LastName',
    'Street1',
    'Street2',
    'City',
    'State',
    'Zip',
    'Country',
    'Phone',
  ],
  Suppliers_ListBuyers: ['Name', 'ID'],
  SupplierUserGroups_List: ['Name', 'ID'],
  SupplierUsers_List: [
    'LastName',
    'FirstName',
    'Username',
    'ID',
    'Email',
    'DateCreated',
    'PasswordLastSetDate',
  ],
  AdminUserGroups_List: ['Name', 'ID'],
  Webhooks_List: ['Name', 'ID'],
  XpIndices_List: ['ThingType', 'Key'],
};

export const getValidSortKey = (
  schema: keyof typeof SORT_MAP,
  sortKey: string,
): boolean => {
  if (SORT_MAP[schema]?.[0] === '*') {
    return true;
  }

  return SORT_MAP[schema].includes(sortKey);
};
